### PR TITLE
Allow FALSE [IF] to start conditional comment blocks

### PR DESCRIPTION
**Pull request by dkearns**

### CODE REVIEW

**Comment by jkotlinski** [comment]
`FALSE [IF]` strikes me as odd, I do not see why anyone would use that for commenting out a chunk of code. `0 [IF]` is way less typing. Has `FALSE [IF]` been spotted in the wild?

**Comment by jkotlinski** [comment]
A quick Github code search answers: yes, that code is in the wild.

**Comment by dkearns** [comment]
Yes, I seem to have a 3 to 1 ratio of 0 to FALSE in my Forth test corpus.

Is your reluctance based on a general dislike of the feature.

I don't use it but would personally have highlighted the flag and conditional words normally and just the discarded area as a comment.

It should terminate at [ELSE] as well.  I'll fix that.

We should consider putting it behind a documented flag like `forth_pseudo_block_comments` or similar.  Perhaps it would need to default to on for backwards compatibility but expecting the user to comment it out isn't particularly friendly.

**Comment by jkotlinski** [comment]
I was just a little bit surprised, because I never saw the pattern `FALSE [IF]` before. But it is not a surprise anymore.

In the code, there is the comment "remove this if it is too much", I did not write that comment and I do not think it is too much :-)

The larger question is how far to go about it, because there are plenty similar patterns that would make equal sense to match, for example `1 [IF] .. [ELSE] .. [THEN]`. Also, what about nested comments? I do not intend to push it further, but someone who is ambitious, could clearly do a lot on it.

**Pull request merged**
